################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           magento
  MYSQL_ROOT_PASSWORD:      magento
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1

################################################################
# Defined Pipeline Stages
stages:
  - tests
  - deploy

################################################################
# Functional Tests
################################################################

.functionnal:   &functionnal
    when:       manual
    stage:      tests
    tags:       ['Dedicated']
#    artifacts:
#      paths:
#        - $CI_PROJECT_DIR/splash.json
#        - $CI_PROJECT_DIR/splash.yml
    services:
      - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
        # Setup Apache Server
        - echo '127.0.0.1 latest.magento.local' >> /etc/hosts
        - cat /etc/hosts
        # Build Module (Composer)
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh | sh
        # Move Module to Magento Dir
        - shopt -s dotglob  # for considering dot files (turn on dot files)
        - cp -Rf $CI_PROJECT_DIR/* /var/www/html/
        - cd /var/www/html
        # Install N89 Mage Run
        - bash /var/www/html/ci/scripts/install_magerun.sh
        # Install Magento
        - bash /var/www/html/ci/scripts/install_magento.sh
        # Configure Apache
        - bash /var/www/html/ci/scripts/config_apache.sh
        # Configure Magento
        - bash /var/www/html/ci/scripts/config_magento.sh
    ################################################################
    # Test Script
    script:
      # Restart Apache Server
      - service apache2 restart && service apache2 status
      - cd $CI_PROJECT_DIR
      ################################################################################
      # Run Grumphp Main Test Sequence
      - php app/code/local/SplashSync/Splash/vendor/bin/grumphp run -n --testsuite=travis
      # Run Grumphp CsFixer Test Sequence
      - php app/code/local/SplashSync/Splash/vendor/bin/grumphp run -n --testsuite=csfixer
      ################################################################################
      # Run Grumphp Php Stan Test Sequence
      - cd /var/www/html
      - php app/code/local/SplashSync/Splash/vendor/bin/grumphp run -n --testsuite=phpstan
      ################################################################################
      # Run PhpUnit Test Sequence
      - php app/code/local/SplashSync/Splash/vendor/bin/phpunit

    ################################################################################
    # Run After Script
    after_script:
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh
        - bash /var/www/html/ci/gitlab/after.sh

Mage-1.9.4-Php-7.2:
  image:      registry.gitlab.com/badpixxel-projects/php-sdk:php-7.2
  variables:
      MAGENTO_VERSION:      magento-mirror-1.9.4.1
  <<: *functionnal

#################################################################
## Build Documentation
#################################################################
pages:
#  when:       manual
  image:      registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
  stage:      deploy
  tags:       ['Dedicated']
  retry:      2
  services:
      - docker:dind
  ################################################################################
  # Run Test Script
  script:
      # Run Composer to Build deps
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
      # Build Documentation
      - php app/code/local/SplashSync/Splash/vendor/bin/grumphp run --tasks=build-docs
  artifacts:
      paths:
          - public

##################################################################
### Build Documentation
##################################################################
#module:
#  image:      registry.gitlab.com/splashsync/php-console:pages
#  stage:      deploy
#  tags:       ['Dedicated']
#  retry:      2
#  services:
#    - docker:dind
#  ################################################################################
#  # Run Test Script
#  script:
#    # Run Composer to Build deps
#    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#    # Build Documentation
#    - php modules/splashsync/vendor/bin/grumphp run --tasks=build-module
#  artifacts:
#    paths:
#      - build
