################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           magento
  MYSQL_ROOT_PASSWORD:      magento
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1

################################################################
# Defined Pipeline Stages
stages:
  - tests
#  - deploy

################################################################
# Functional Tests
################################################################

.functionnal:   &functionnal
#    when:       manual
    stage:      tests
    tags:       ['Dedicated']
#    artifacts:
#      paths:
#        - $CI_PROJECT_DIR/splash.json
#        - $CI_PROJECT_DIR/splash.yml
    services:
      - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
        # Move Module
        - cp -Rf $CI_PROJECT_DIR/ /var/www/html
        - ls -l /var/www/html
        # Build Module (Composer)
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh | sh
        # Install N89 Mage Run
        - bash /var/www/html/ci/scripts/install_magerun.sh
        # Install Magento
        - bash /var/www/html/ci/scripts/install_magento.sh
        # Configure Apache
        - bash /var/www/html/ci/scripts/config_apache.sh
        # Configure Magento
        - bash /var/www/html/ci/scripts/config_magento.sh
    ################################################################
    # Test Script
    script:
      - pwd
      - cd /var/www/html
      - ls -l
#      - cd $TMP_DIR
#      ################################################################################
#      # Build Module (Composer)
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh | sh
#      ################################################################################
#      # Install Prestashop + WebServer (Apache & PHP-Fpm)
#      - cat $CI_PROJECT_DIR/docker/docker-entrypoint.sh | bash
#      ################################################################################
#      # Install Module
#      - bash $SCRIPTS_DIR/module/install.sh
#      ################################################################################
#      # Run Grumphp Main Test Sequence
#      - cd $TMP_DIR
#      - php modules/splashsync/vendor/bin/grumphp run -n --testsuite=travis
#      ################################################################################
#      # Run Grumphp CsFixer Test Sequence
#      - cd $TRAVIS_BUILD_DIR
#      - composer install
#      - php modules/splashsync/vendor/bin/grumphp run -n --testsuite=csfixer
#      ################################################################################
#      # Run Grumphp Php Stan Test Sequence
#      - if [ -f "/var/www/html/vendor/autoload.php" ]; then php modules/splashsync/vendor/bin/grumphp run -n --testsuite=phpstan; fi
#      ################################################################################
#      # Run PhpUnit Core Test Sequence (Will Enable the Module)
#      - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist modules/splashsync/vendor/splash/phpcore/Tests/Core/
#      ################################################################################
#      # ALL PHP   =>  Run PhpUnit Local Sequence with No Data Inside
#      - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist --testsuite=Local
#      ################################################################################
#      # Run PhpUnit Test Sequence (With Coverage)
#      - php modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist
#      ################################################################################
#      # Run PhpUnit Product with MSF Sequence
#      - php travis/setup_shops.php && php travis/setup_shops.php
#      - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.products.xml
#      ################################################################################
#      # Run Grumphp Splash Manifest Sequence
#      - php modules/splashsync/vendor/bin/grumphp run -n --tasks=build-manifest

    ################################################################################
    # Run After Script
    after_script:
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh
        - bash /var/www/html/ci/gitlab/after.sh

Mage-1.9.4-Php-7.2:
  image:      registry.gitlab.com/badpixxel-projects/php-sdk:php-7.2
  variables:
      MAGENTO_VERSION:      magento-mirror-1.9.4.1
  <<: *functionnal

#Ps-1.7-Php-7.2:
#  image:      prestashop/prestashop:1.7-7.2-apache
#  <<: *functionnal
#
#Ps-1.6-Php-7.2:
#  image:      prestashop/prestashop:1.6-7.2-apache
#  <<: *functionnal


##################################################################
### Build Documentation
##################################################################
#pages:
#  image:      registry.gitlab.com/splashsync/php-console:pages
#  stage:      deploy
#  tags:       ['Dedicated']
#  retry:      2
#  services:
#    - docker:dind
#  ################################################################################
#  # Run Test Script
#  script:
#    # Run Composer to Build deps
#    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#    # Build Documentation
#    - php modules/splashsync/vendor/bin/grumphp run --tasks=build-docs
#  artifacts:
#    paths:
#      - public
#
##################################################################
### Build Documentation
##################################################################
#module:
#  image:      registry.gitlab.com/splashsync/php-console:pages
#  stage:      deploy
#  tags:       ['Dedicated']
#  retry:      2
#  services:
#    - docker:dind
#  ################################################################################
#  # Run Test Script
#  script:
#    # Run Composer to Build deps
#    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#    # Build Documentation
#    - php modules/splashsync/vendor/bin/grumphp run --tasks=build-module
#  artifacts:
#    paths:
#      - build
