# Tell Travis CI we're using PHP
language: php
os: linux

# Tell Travis CI we're using MySQL
services:
  - mysql
  
# Tell Travis CI we're using Cache
cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:

#        # Magento 1.8 Branch       
#        - php: 5.6
#          env: MAGENTO_VERSION=magento-mirror-1.8.1.0    

        # Magento 1.9 Branch (For Horace)       
        - php: 5.6
          env: MAGENTO_VERSION=magento-mirror-1.9.1.0    

        # Magento 1.9 Branch (For prop Sailing)       
        - php: 5.6
          env: MAGENTO_VERSION=magento-mirror-1.9.4.1  
          
        # Magento 1.9 Branch       
        - php: 5.6
          env: MAGENTO_VERSION=magento-mirror-1.9.0.1    
        - php: 5.6
          env: MAGENTO_VERSION=magento-mirror-1.9.3.6    
        - php: 7.0
          env: MAGENTO_VERSION=magento-mirror-1.9.3.6    
        - php: 7.1
          env: MAGENTO_VERSION=magento-mirror-1.9.3.6    
          
    allow_failures:
        - php: 7.0
        - php: 7.1
          
    fast_finish: true
    
install:
    # Configure Php ...
    - phpenv config-rm xdebug.ini
    - phpenv config-add build/x_memory.ini    
    
    # With PHP 7 => Load Phpstan   
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require phpstan/phpstan-shim 0.9.2 --no-update; fi
    
    # Run Composer
    - composer update
    
    # Install Magento & Modules
    - sh build/setup.sh
    
    # Configure Splash Module
    - sh build/configure.sh    

script:
    - cd /tmp/magetest/htdocs
    
    # With PHP 7 => Execute Phpstan 
    - php ./app/code/local/SplashSync/Splash/vendor/bin/grumphp run  --testsuite=travis
    
    # With PHP 7 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then php ./app/code/local/SplashSync/Splash/vendor/bin/grumphp run --testsuite=phpstan; fi       
    
    # Execute Functional Tests
#    - phpunit
    - php ./app/code/local/SplashSync/Splash/vendor/bin/phpunit
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:
    
    # Print Installation Infos
    - phpunit --version
    - php -r "echo date_default_timezone_get();"
    - cd /tmp/magetest
    - ./n98-magerun.phar --version
    - ./n98-magerun.phar --root-dir=htdocs sys:info   
    - ./n98-magerun.phar --root-dir=htdocs sys:store:list   
    - ./n98-magerun.phar --root-dir=htdocs sys:modules:list   
    - ./n98-magerun.phar --root-dir=htdocs eav:attribute:list
    - ./n98-magerun.phar --root-dir=htdocs config:get general/store_information/*     
    - ./n98-magerun.phar --root-dir=htdocs config:get general/locale/*     
