<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css'); ?>" media="all" />

<div class="content-header">
    <h3 >Languages Mapping</h3>
</div>    

<div class="grid">
    <div class="hor-scroll">
        
    <?php if ( !Mage::getStoreConfig('splashsync_splash_options/langs/multilang') ) {  ?>
        <p>Single Language Mode</p>
    <?php } else { ?>
        <p>Multi-Language Mode</p>
        
            
            
        <table cellspacing="0" class="data" id="cmsBlockGrid_table">
            <thead>
                <tr class="headings">
                    <th><span class="nobr"><span class="sort-title">WebSite</span></span></th>
                    <th><span class="nobr"><span class="sort-title">Store</span></span></th>
                    <th><span class="nobr"><span class="sort-title">Store View</span></span></th>
                    <th><span class="nobr"><span class="sort-title">Language</span></span></th>
                </tr>
            </thead>
            <tbody>
            <?php 
                foreach (Mage::app()->getWebsites() as $Website) {
                    foreach ($Website->getGroups() as $Group) {
                        foreach ($Group->getStores() as $Store) {
            ?>
                <tr>
                    <td class="a-left "><?php echo $Website->getName(); ?></td>
                    <td class="a-left "><?php echo $Group->getName(); ?></td>
                    <td class="a-left "><?php echo $Store->getName(); ?></td>
                    <td class="a-left "><?php echo $Store->getConfig('splashsync_splash_options/langs/store_lang'); ?></td>
                </tr>
                <?php }}} ?>            
            </tbody>
        </table>
    <?php } ?>   
    </div>
</div>


                
                

