
<div class="content-header">
    <h3 >Remote Server to Websites Mapping</h3>
</div>    

<div class="grid">
    <div class="hor-scroll">
        <table cellspacing="0" class="data" id="cmsBlockGrid_table">
            <thead>
                <tr class="headings">
                    <th><span class="nobr"><span class="sort-title">WebSite</span></span></th>
                    <th><span class="nobr"><span class="sort-title">Origin Node</span></span></th>
                </tr>
            </thead>
            <tbody>
            <?php 
                foreach (Mage::app()->getWebsites() as $Website) {
            ?>
                <tr>
                    <td class="a-left "><?php echo $Website->getName(); ?></td>
                    <td class="a-left "><?php echo $Website->getConfig('splashsync_splash_options/thirdparty/origin'); ?></td>
                </tr>
            <?php } ?>            
            </tbody>
        </table>
    </div>
</div>


                
                

