<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css'); ?>" media="all" />

<div class="content-header">
    <h3 >Module Self Tests</h3>
</div>    

<div class="grid">
    <div class="hor-scroll">
        <table cellspacing="0" class="data" id="cmsBlockGrid_table">
            <thead>
                <tr class="headings">
                    <th><span class="nobr"><span class="sort-title">Id</span></span></th>
                    <th><span class="nobr"><span class="sort-title">Title</span></span></th>
                    <th><span class="nobr"><span class="sort-title">Description</span></span></th>
                    <th><span class="nobr"><span class="sort-title">Status</span></span></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ( $this->getResults() as $Result ) { ?>
                <tr>
                    <td class="a-left "><?php echo $Result["id"]; ?></td>
                    <td class="a-left "><?php echo $Result["name"]; ?></td>
                    <td class="a-left "><?php echo $Result["desc"]; ?></td>
                    <td class="a-left "><?php echo $Result["result"]; ?></td>
                </tr>
            <?php } ?>            
            </tbody>
        </table>
    </div>
</div>

<div id="messages">
    <ul class="messages">
    <?php if ( isset($this->getMessages()->err) ) { foreach ( $this->getMessages()->err as $Text ) { ?>
        <li class="error-msg"><ul><li><span><?php echo $Text; ?></span></li></ul></li>
    <?php }} ?>   
    <?php if ( isset($this->getMessages()->war) ) { foreach ( $this->getMessages()->war as $Text ) { ?>
        <li class="warning-msg"><ul><li><span><?php echo $Text; ?></span></li></ul></li>
    <?php }} ?>   
    <?php if ( isset($this->getMessages()->msg) ) { foreach ( $this->getMessages()->msg as $Text ) { ?>
        <li class="success-msg"><ul><li><span><?php echo $Text; ?></span></li></ul></li>
    <?php }} ?>   
    <?php if ( isset($this->getMessages()->deb) ) { foreach ( $this->getMessages()->deb as $Text ) { ?>
        <li class="success-msg"><ul><li><span><?php echo $Text; ?></span></li></ul></li>
    <?php }} ?>   
    </ul>
</div>

                
                

